
import { GoogleGenAI } from "@google/genai";

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({
      error: "Method not allowed"
    });
  }

  try {
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return res.status(500).json({
        error: "GEMINI_API_KEY is not configured in Vercel."
      });
    }

    const prompt = String(
      req.body?.prompt || ""
    ).trim();

    if (!prompt) {
      return res.status(400).json({
        error: "Please describe the image you want."
      });
    }

    if (prompt.length > 3000) {
      return res.status(400).json({
        error: "Image prompt is too long."
      });
    }

    const ai = new GoogleGenAI({
      apiKey
    });

    const response = await ai.models.generateContent({
      model: "gemini-3.1-flash-image",
      contents: prompt,
      config: {
        responseModalities: ["TEXT", "IMAGE"]
      }
    });

    let imageData = null;
    let mimeType = "image/png";
    let generatedText = "";

    const parts =
      response.candidates?.[0]?.content?.parts || [];

    for (const part of parts) {

      if (part.text) {
        generatedText += part.text;
      }

      if (part.inlineData) {
        imageData = part.inlineData.data;
        mimeType =
          part.inlineData.mimeType ||
          "image/png";
      }
    }

    if (!imageData) {
      return res.status(502).json({
        error:
          "ZenX.AI could not generate an image."
      });
    }

    res.setHeader(
      "Cache-Control",
      "no-store"
    );

    return res.status(200).json({
      image:
        `data:${mimeType};base64,${imageData}`,

      text:
        generatedText ||
        "Image generated by ZenX.AI."
    });

  } catch (error) {

    console.error(
      "ZenX image error:",
      error
    );

    return res.status(500).json({
      error:
        error?.message ||
        "Image generation failed."
    });
  }
}
